// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x852deD011285fe67063a08005c71a85690503Cee (OssifiableProxy) → implementation 0xe4f03D1107d1905B6F2A28FCb6Af221E0CE19136 (AccountingOracle)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IAccountingOracle {
    struct ReportData {
        uint256 consensusVersion;
        uint256 refSlot;
        uint256 clValidatorsBalanceGwei;
        uint256 clPendingBalanceGwei;
        uint256[] stakingModuleIdsWithNewlyExitedValidators;
        uint256[] numExitedValidatorsByStakingModule;
        uint256[] stakingModuleIdsWithUpdatedBalance;
        uint256[] validatorBalancesGweiByStakingModule;
        uint256 withdrawalVaultBalance;
        uint256 elRewardsVaultBalance;
        uint256 sharesRequestedToBurn;
        uint256[] withdrawalFinalizationBatches;
        uint256 simulatedShareRate;
        bool isBunkerMode;
        bytes32 vaultsDataTreeRoot;
        string vaultsDataTreeCid;
        uint256 extraDataFormat;
        bytes32 extraDataHash;
        uint256 extraDataItemsCount;
    }

    function discardConsensusReport(uint256 refSlot) external;

    function finalizeUpgrade_v5(uint256 consensusVersion) external;

    function grantRole(bytes32 role, address account) external;

    function initialize(
        address admin,
        address consensusContract,
        uint256 consensusVersion,
        uint256 lastProcessingRefSlot
    ) external;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function setConsensusContract(address addr) external;

    function setConsensusVersion(uint256 version) external;

    function submitConsensusReport(bytes32 reportHash, uint256 refSlot, uint256 deadline) external;

    function submitReportData(ReportData calldata data, uint256 contractVersion) external;

    function submitReportExtraDataEmpty() external;

    function submitReportExtraDataList(bytes calldata data) external;
}
