// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x9895F0F17cc1d1891b6f18ee0b483B6f221b37Bb (AppProxyUpgradeable) → implementation 0x9f3b9198911054b122fdb865f8a5ac516201c339 (ACL)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IACL {
    function grantPermission(address _entity, address _app, bytes32 _role) external;

    function grantPermissionP(address _entity, address _app, bytes32 _role, uint256[] calldata _params) external;

    function revokePermission(address _entity, address _app, bytes32 _role) external;

    function setPermissionManager(address _newManager, address _app, bytes32 _role) external;

    function createPermission(address _entity, address _app, bytes32 _role, address _manager) external;
}
