// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c (AppProxyUpgradeable) → implementation 0x3A93C17FC82CC33420d1809dDA9Fb715cc89dd37 (Agent)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IAgent {
    function onERC721Received(
        address _operator,
        address _from,
        uint256 _tokenId,
        bytes calldata _data
    ) external returns (bytes4);

    function deposit(address _token, uint256 _value) external payable;

    function presignHash(bytes32 _hash) external;

    function removeProtectedToken(address _token) external;

    function addProtectedToken(address _token) external;

    function initialize() external;

    function transferToVault(address _token) external;

    function setDesignatedSigner(address _designatedSigner) external;

    function safeExecute(address _target, bytes calldata _data) external;

    function execute(address _target, uint256 _ethValue, bytes calldata _data) external;

    function transfer(address _token, address _to, uint256 _value) external;

    function forward(bytes calldata _evmScript) external;
}
