// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x1a7cFA9EFB4D5BfFDE87B0FaEb1fC65d653868C0 (AllowedRecipientsRegistry)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IAllowedRecipientsRegistry {
    function addRecipient(address _recipient, string calldata _title) external;

    function grantRole(bytes32 role, address account) external;

    function removeRecipient(address _recipient) external;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function setBokkyPooBahsDateTimeContract(address _bokkyPooBahsDateTimeContract) external;

    function setLimitParameters(uint256 _limit, uint256 _periodDurationMonths) external;

    function unsafeSetSpentAmount(uint256 _newSpentAmount) external;

    function updateSpentAmount(uint256 _payoutAmount) external;
}
