// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x3B525F4c059F246Ca4aa995D21087204F30c9E2F (AllowedRecipientsRegistry)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IAllowedRecipientsRegistry {
    function addRecipient(address _recipient, string calldata _title) external;

    function removeRecipient(address _recipient) external;

    function setLimitParameters(uint256 _limit, uint256 _periodDurationMonths) external;

    function updateSpentAmount(uint256 _payoutAmount) external;
}
