// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xE76c52750019b80B43E36DF30bf4060EB73F573a (OssifiableProxy) → implementation 0xEe1E3B4f047122650086985f794f0dB5f10Ae49D (Burner)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IBurner {
    function commitSharesToBurn(uint256 _sharesToBurn) external;

    function grantRole(bytes32 role, address account) external;

    function initialize(address _admin, bool _isMigrationAllowed) external;

    function migrate(address _oldBurner) external;

    function recoverERC20(address _token, uint256 _amount) external;

    function recoverERC721(address _token, uint256 _tokenId) external;

    function recoverExcessStETH() external;

    function renounceRole(bytes32 role, address account) external;

    function requestBurnMyShares(uint256 _sharesAmountToBurn) external;

    function requestBurnMyStETH(uint256 _stETHAmountToBurn) external;

    function requestBurnMyStETHForCover(uint256 _stETHAmountToBurn) external;

    function requestBurnShares(address _from, uint256 _sharesAmountToBurn) external;

    function requestBurnSharesForCover(address _from, uint256 _sharesAmountToBurn) external;

    function revokeRole(bytes32 role, address account) external;
}
