// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x6019CB557978296BA3C08a7B73225C0975DFB2F7 (CircuitBreaker)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ICircuitBreaker {
    function heartbeat() external;

    function pause(address _pausable) external;

    function registerPauser(address _pausable, address _newPauser) external;

    function setHeartbeatInterval(uint256 _newHeartbeatInterval) external;

    function setPauseDuration(uint256 _newPauseDuration) external;
}
