// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x4d72BFF1BeaC69925F8Bd12526a39BAAb069e5Da (OssifiableProxy) → implementation 0xe768572cc5aE5C698345C59288d871a949Ea8bd3 (Accounting)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ICSAccounting {
    struct BondCurveIntervalInput {
        uint256 minKeysCount;
        uint256 trend;
    }

    struct PermitInput {
        uint256 value;
        uint256 deadline;
        uint8 v;
        bytes32 r;
        bytes32 s;
    }

    struct FeeSplit {
        address recipient;
        uint256 share;
    }

    function addBondCurve(BondCurveIntervalInput[] calldata bondCurve) external returns (uint256 id);

    function chargeFee(uint256 nodeOperatorId, uint256 amount) external returns (bool);

    function claimRewardsStETH(
        uint256 nodeOperatorId,
        uint256 stETHAmount,
        uint256 cumulativeFeeShares,
        bytes32[] calldata rewardsProof
    ) external returns (uint256 claimedShares);

    function claimRewardsUnstETH(
        uint256 nodeOperatorId,
        uint256 stETHAmount,
        uint256 cumulativeFeeShares,
        bytes32[] calldata rewardsProof
    ) external returns (uint256 requestId);

    function claimRewardsWstETH(
        uint256 nodeOperatorId,
        uint256 wstETHAmount,
        uint256 cumulativeFeeShares,
        bytes32[] calldata rewardsProof
    ) external returns (uint256 claimedWstETH);

    function compensateLockedBond(uint256 nodeOperatorId) external returns (uint256 compensatedAmount);

    function depositETH(address from, uint256 nodeOperatorId) external payable;

    function depositETH(uint256 nodeOperatorId) external payable;

    function depositStETH(
        address from,
        uint256 nodeOperatorId,
        uint256 stETHAmount,
        PermitInput calldata permit
    ) external;

    function depositStETH(uint256 nodeOperatorId, uint256 stETHAmount, PermitInput calldata permit) external;

    function depositWstETH(uint256 nodeOperatorId, uint256 wstETHAmount, PermitInput calldata permit) external;

    function depositWstETH(
        address from,
        uint256 nodeOperatorId,
        uint256 wstETHAmount,
        PermitInput calldata permit
    ) external;

    function finalizeUpgradeV3() external;

    function grantRole(bytes32 role, address account) external;

    function initialize(
        BondCurveIntervalInput[] calldata bondCurve,
        address admin,
        uint256 bondLockPeriod,
        address _chargePenaltyRecipient
    ) external;

    function lockBond(uint256 nodeOperatorId, uint256 amount) external;

    function pauseFor(uint256 duration) external;

    function penalize(uint256 nodeOperatorId, uint256 amount) external returns (bool penaltyCovered);

    function pullAndSplitFeeRewards(
        uint256 nodeOperatorId,
        uint256 cumulativeFeeShares,
        bytes32[] calldata rewardsProof
    ) external;

    function recoverERC1155(address token, uint256 tokenId) external;

    function recoverERC20(address token, uint256 amount) external;

    function recoverERC721(address token, uint256 tokenId) external;

    function recoverEther() external;

    function recoverStETHShares() external;

    function releaseLockedBond(uint256 nodeOperatorId, uint256 amount) external returns (bool released);

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function setBondCurve(uint256 nodeOperatorId, uint256 curveId) external;

    function setBondLockPeriod(uint256 period) external;

    function setChargePenaltyRecipient(address _chargePenaltyRecipient) external;

    function setCustomRewardsClaimer(uint256 nodeOperatorId, address rewardsClaimer) external;

    function settleLockedBond(uint256 nodeOperatorId, uint256 bondLockNonce) external returns (uint256);

    function unlockExpiredLock(uint256 nodeOperatorId) external;

    function updateBondCurve(uint256 curveId, BondCurveIntervalInput[] calldata bondCurve) external;

    function updateFeeSplits(
        uint256 nodeOperatorId,
        FeeSplit[] calldata feeSplits,
        uint256 cumulativeFeeShares,
        bytes32[] calldata rewardsProof
    ) external;
}
