// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x4D4074628678Bd302921c20573EEa1ed38DdF7FB (OssifiableProxy) → implementation 0xecE6e0Cde61078F76b66Ef0C338a6875E5D01F79 (FeeOracle)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ICSFeeOracle {
    struct ReportData {
        uint256 consensusVersion;
        uint256 refSlot;
        bytes32 treeRoot;
        string treeCid;
        string logCid;
        uint256 distributed;
        uint256 rebate;
        bytes32 strikesTreeRoot;
        string strikesTreeCid;
    }

    function discardConsensusReport(uint256 refSlot) external;

    function finalizeUpgradeV3(uint256 consensusVersion) external;

    function grantRole(bytes32 role, address account) external;

    function initialize(address admin, address consensusContract, uint256 consensusVersion) external;

    function pauseFor(uint256 duration) external;

    function recoverERC1155(address token, uint256 tokenId) external;

    function recoverERC20(address token, uint256 amount) external;

    function recoverERC721(address token, uint256 tokenId) external;

    function recoverEther() external;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function setConsensusContract(address addr) external;

    function setConsensusVersion(uint256 version) external;

    function submitConsensusReport(bytes32 reportHash, uint256 refSlot, uint256 deadline) external;

    function submitReportData(ReportData calldata data, uint256 contractVersion) external;
}
