// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xdA7dE2ECdDfccC6c3AF10108Db212ACBBf9EA83F (OssifiableProxy) → implementation 0x63992a86f009fcC796a8369feEfB68880aef4e3a (CSModule)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ICSModule {
    struct PermitInput {
        uint256 value;
        uint256 deadline;
        uint8 v;
        bytes32 r;
        bytes32 s;
    }

    struct NodeOperatorManagementProperties {
        address managerAddress;
        address rewardAddress;
        bool extendedManagerPermissions;
    }

    struct WithdrawnValidatorInfo {
        uint256 nodeOperatorId;
        uint256 keyIndex;
        uint256 exitBalance;
        uint256 slashingPenalty;
        bool isSlashed;
    }

    function addValidatorKeysETH(
        address from,
        uint256 nodeOperatorId,
        uint256 keysCount,
        bytes calldata publicKeys,
        bytes calldata signatures
    ) external payable;

    function addValidatorKeysStETH(
        address from,
        uint256 nodeOperatorId,
        uint256 keysCount,
        bytes calldata publicKeys,
        bytes calldata signatures,
        PermitInput calldata permit
    ) external;

    function addValidatorKeysWstETH(
        address from,
        uint256 nodeOperatorId,
        uint256 keysCount,
        bytes calldata publicKeys,
        bytes calldata signatures,
        PermitInput calldata permit
    ) external;

    function allocateDeposits(
        uint256 maxDepositAmount,
        bytes[] calldata pubkeys,
        uint256[] calldata keyIndices,
        uint256[] calldata operatorIds,
        uint256[] calldata topUpLimits
    ) external returns (uint256[] memory allocations);

    function batchDepositInfoUpdate(uint256 maxCount) external returns (uint256 operatorsLeft);

    function cancelGeneralDelayedPenalty(uint256 nodeOperatorId, uint256 amount) external;

    function changeNodeOperatorAddresses(
        uint256 nodeOperatorId,
        address newManagerAddress,
        address newRewardAddress
    ) external;

    function changeNodeOperatorRewardAddress(uint256 nodeOperatorId, address newAddress) external;

    function cleanDepositQueue(uint256 maxItems) external returns (uint256 removed, uint256 lastRemovedAtDepth);

    function compensateGeneralDelayedPenalty(uint256 nodeOperatorId) external;

    function confirmNodeOperatorManagerAddressChange(uint256 nodeOperatorId) external;

    function confirmNodeOperatorRewardAddressChange(uint256 nodeOperatorId) external;

    function createNodeOperator(
        address from,
        NodeOperatorManagementProperties calldata managementProperties,
        address referrer
    ) external returns (uint256 nodeOperatorId);

    function decreaseVettedSigningKeysCount(
        bytes calldata nodeOperatorIds,
        bytes calldata vettedSigningKeysCounts
    ) external;

    function finalizeUpgradeV3() external;

    function grantRole(bytes32 role, address account) external;

    function initialize(address admin, uint8 topUpQueueLimit) external;

    function obtainDepositData(
        uint256 depositsCount,
        bytes calldata depositCalldata
    ) external returns (bytes memory publicKeys, bytes memory signatures);

    function onRewardsMinted(uint256 totalShares) external;

    function onValidatorExitTriggered(
        uint256 nodeOperatorId,
        bytes calldata publicKey,
        uint256 elWithdrawalRequestFeePaid,
        uint256 exitType
    ) external;

    function pauseFor(uint256 duration) external;

    function proposeNodeOperatorManagerAddressChange(uint256 nodeOperatorId, address proposedAddress) external;

    function proposeNodeOperatorRewardAddressChange(uint256 nodeOperatorId, address proposedAddress) external;

    function rebuildTotalWithdrawnValidators() external;

    function recoverERC1155(address token, uint256 tokenId) external;

    function recoverERC20(address token, uint256 amount) external;

    function recoverERC721(address token, uint256 tokenId) external;

    function recoverEther() external;

    function removeKeys(uint256 nodeOperatorId, uint256 startIndex, uint256 keysCount) external;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function reportGeneralDelayedPenalty(
        uint256 nodeOperatorId,
        bytes32 penaltyType,
        uint256 amount,
        string calldata details
    ) external;

    function reportRegularWithdrawnValidators(WithdrawnValidatorInfo[] calldata validatorInfos) external;

    function reportSlashedWithdrawnValidators(WithdrawnValidatorInfo[] calldata validatorInfos) external;

    function reportValidatorBalance(uint256 nodeOperatorId, uint256 keyIndex, uint256 currentBalanceWei) external;

    function reportValidatorExitDelay(
        uint256 nodeOperatorId,
        uint256 proofSlotTimestamp,
        bytes calldata publicKey,
        uint256 eligibleToExitInSec
    ) external;

    function reportValidatorSlashing(uint256 nodeOperatorId, uint256 keyIndex) external;

    function requestFullDepositInfoUpdate() external;

    function resetNodeOperatorManagerAddress(uint256 nodeOperatorId) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function rewindTopUpQueue(uint256 to) external;

    function setTopUpQueueLimit(uint256 limit) external;

    function settleGeneralDelayedPenalty(uint256[] calldata nodeOperatorIds, uint256[] calldata bondLockNonces) external;

    function unsafeUpdateValidatorsCount(uint256 nodeOperatorId, uint256 exitedValidatorsCount) external;

    function updateDepositInfo(uint256 nodeOperatorId) external;

    function updateDepositableValidatorsCount(uint256 nodeOperatorId) external;

    function updateExitedValidatorsCount(bytes calldata nodeOperatorIds, bytes calldata exitedValidatorsCounts) external;

    function updateTargetValidatorsLimits(uint256 nodeOperatorId, uint256 targetLimitMode, uint256 targetLimit) external;
}
