// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xfFA96D84dEF2EA035c7AB153D8B991128e3d72fD (DepositSecurityModule)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IDepositSecurityModule {
    struct Signature {
        bytes32 r;
        bytes32 vs;
    }

    function addGuardian(address addr, uint256 newQuorum) external;

    function addGuardians(address[] calldata addresses, uint256 newQuorum) external;

    function depositBufferedEther(
        uint256 blockNumber,
        bytes32 blockHash,
        bytes32 depositRoot,
        uint256 stakingModuleId,
        uint256 nonce,
        bytes calldata depositCalldata,
        Signature[] calldata sortedGuardianSignatures
    ) external;

    function pauseDeposits(uint256 blockNumber, Signature calldata sig) external;

    function removeGuardian(address addr, uint256 newQuorum) external;

    function setGuardianQuorum(uint256 newValue) external;

    function setMaxOperatorsPerUnvetting(uint256 newValue) external;

    function setOwner(address newValue) external;

    function setPauseIntentValidityPeriodBlocks(uint256 newValue) external;

    function unpauseDeposits() external;

    function unvetSigningKeys(
        uint256 blockNumber,
        bytes32 blockHash,
        uint256 stakingModuleId,
        uint256 nonce,
        bytes calldata nodeOperatorIds,
        bytes calldata vettedSigningKeysCounts,
        Signature calldata sig
    ) external;
}
