// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xF0211b7660680B49De1A7E9f25C65660F0a13Fea (EasyTrack)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IEasyTrack {
    function addEVMScriptFactory(address _evmScriptFactory, bytes calldata _permissions) external;

    function cancelAllMotions() external;

    function cancelMotion(uint256 _motionId) external;

    function cancelMotions(uint256[] calldata _motionIds) external;

    function createMotion(
        address _evmScriptFactory,
        bytes calldata _evmScriptCallData
    ) external returns (uint256 _newMotionId);

    function enactMotion(uint256 _motionId, bytes calldata _evmScriptCallData) external;

    function grantRole(bytes32 role, address account) external;

    function objectToMotion(uint256 _motionId) external;

    function pause() external;

    function removeEVMScriptFactory(address _evmScriptFactory) external;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function setEVMScriptExecutor(address _evmScriptExecutor) external;

    function setMotionDuration(uint256 _motionDuration) external;

    function setMotionsCountLimit(uint256 _motionsCountLimit) external;

    function setObjectionsThreshold(uint256 _objectionsThreshold) external;

    function unpause() external;
}
