// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xCE0425301C85c5Ea2A0873A2dEe44d78E02D2316 (EmergencyProtectedTimelock)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IEmergencyProtectedTimelock {
    function setEmergencyProtectionEndDate(uint40 newEmergencyProtectionEndDate) external;
}
