// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xB9E5CBB9CA5b0d659238807E84D0176930753d86 (AppProxyUpgradeable) → implementation 0x836835289A2E81B66AE5d95b7c8dBC0480dCf9da (Finance)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IFinance {
    function newScheduledPayment(
        address _token,
        address _receiver,
        uint256 _amount,
        uint64 _initialPaymentTime,
        uint64 _interval,
        uint64 _maxExecutions,
        string calldata _reference
    ) external returns (uint256 paymentId);

    function executePayment(uint256 _paymentId) external;

    function initialize(address _vault, uint64 _periodDuration) external;

    function removeBudget(address _token) external;

    function setPaymentStatus(uint256 _paymentId, bool _active) external;

    function receiverExecutePayment(uint256 _paymentId) external;

    function setPeriodDuration(uint64 _periodDuration) external;

    function setBudget(address _token, uint256 _amount) external;

    function recoverToVault(address _token) external;

    function transferToVault(address _token) external;

    function tryTransitionAccountingPeriod(uint64 _maxTransitions) external returns (bool success);

    function deposit(address _token, uint256 _amount, string calldata _reference) external payable;

    function newImmediatePayment(
        address _token,
        address _receiver,
        uint256 _amount,
        string calldata _reference
    ) external;
}
