// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x7FaDB6358950c5fAA66Cb5EB8eE5147De3df355a (HashConsensus)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IHashConsensus {
    function addMember(address addr, uint256 quorum) external;

    function disableConsensus() external;

    function grantRole(bytes32 role, address account) external;

    function removeMember(address addr, uint256 quorum) external;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function setFastLaneLengthSlots(uint256 fastLaneLengthSlots) external;

    function setFrameConfig(uint256 epochsPerFrame, uint256 fastLaneLengthSlots) external;

    function setQuorum(uint256 quorum) external;

    function setReportProcessor(address newProcessor) external;

    function submitReport(uint256 slot, bytes32 report, uint256 consensusVersion) external;

    function updateInitialEpoch(uint256 initialEpoch) external;
}
