// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Existing abi/Kernel.abi.ts, mainnet Kernel 0xb8FFC3Cd6e7Cf5a098A1c92F48009765B24088Dc
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IKernel {
    function setApp(bytes32 _namespace, bytes32 _appId, address _app) external;
}
