// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84 (AppProxyUpgradeable) → implementation 0x028271E30a695c0527A0C50cA30603feD004cDb0 (Lido)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ILido {
    function resume() external;

    function mintExternalShares(address _recipient, uint256 _amountOfShares) external;

    function stop() external;

    function approve(address _spender, uint256 _amount) external returns (bool);

    function setDepositsReserveTarget(uint256 _newDepositsReserveTarget) external;

    function initialize(address _lidoLocator, address _eip712StETH, uint256 _depositsReserveTarget) external payable;

    function emitTokenRebase(
        uint256 _reportTimestamp,
        uint256 _timeElapsed,
        uint256 _preTotalShares,
        uint256 _preTotalEther,
        uint256 _postTotalShares,
        uint256 _postTotalEther,
        uint256 _postInternalShares,
        uint256 _postInternalEther,
        uint256 _sharesMintedAsFees
    ) external;

    function withdrawDepositableEther(uint256 _amount, uint256 _seedDepositsCount) external;

    function transferFrom(address _sender, address _recipient, uint256 _amount) external returns (bool);

    function setStakingLimit(uint256 _maxStakeLimit, uint256 _stakeLimitIncreasePerBlock) external;

    function increaseAllowance(address _spender, uint256 _addedValue) external returns (bool);

    function receiveELRewards() external payable;

    function mintShares(address _recipient, uint256 _amountOfShares) external;

    function processClStateUpdate(
        uint256 _reportTimestamp,
        uint256 _clValidatorsBalance,
        uint256 _clPendingBalance
    ) external;

    function internalizeExternalBadDebt(uint256 _amountOfShares) external;

    function transferSharesFrom(address _sender, address _recipient, uint256 _sharesAmount) external returns (uint256);

    function burnExternalShares(uint256 _amountOfShares) external;

    function resumeStaking() external;

    function receiveWithdrawals() external payable;

    function rebalanceExternalEtherToInternal(uint256 _amountOfShares) external payable;

    function burnShares(uint256 _amountOfShares) external;

    function finalizeUpgrade_v4(uint256 _depositsReserveTarget) external;

    function transferShares(address _recipient, uint256 _sharesAmount) external returns (uint256);

    function collectRewardsAndProcessWithdrawals(
        uint256 _reportTimestamp,
        uint256 _reportClBalance,
        uint256 _principalCLBalance,
        uint256 _withdrawalsToWithdraw,
        uint256 _elRewardsToWithdraw,
        uint256 _lastWithdrawalRequestToFinalize,
        uint256 _withdrawalsShareRate,
        uint256 _etherToLockOnWithdrawalQueue
    ) external;

    function transferToVault(address) external;

    function submit(address _referral) external payable returns (uint256);

    function decreaseAllowance(address _spender, uint256 _subtractedValue) external returns (bool);

    function transfer(address _recipient, uint256 _amount) external returns (bool);

    function removeStakingLimit() external;

    function permit(
        address _owner,
        address _spender,
        uint256 _value,
        uint256 _deadline,
        uint8 _v,
        bytes32 _r,
        bytes32 _s
    ) external;

    function setMaxExternalRatioBP(uint256 _maxExternalRatioBP) external;

    function pauseStaking() external;
}
