// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xF95f069F9AD107938F6ba802a3da87892298610E (Vyper_contract)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IMEVBoostRelayAllowedList {
    function add_relay(
        string calldata uri,
        string calldata operator,
        bool is_mandatory,
        string calldata description
    ) external;

    function remove_relay(string calldata uri) external;

    function change_owner(address owner) external;

    function set_manager(address manager) external;

    function dismiss_manager() external;

    function recover_erc20(address token, uint256 amount, address recipient) external;
}
