// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x55032650b14df07b85bF18A3a3eC8E0Af2e028d5 (AppProxyUpgradeable) → implementation 0x6828b023e737f96B168aCd0b5c6351971a4F81aE (NodeOperatorsRegistry)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface INodeOperatorsRegistry {
    function updateTargetValidatorsLimits(
        uint256 _nodeOperatorId,
        uint256 _targetLimitMode,
        uint256 _targetLimit
    ) external;

    function addSigningKeys(
        uint256 _nodeOperatorId,
        uint256 _keysCount,
        bytes calldata _publicKeys,
        bytes calldata _signatures
    ) external;

    function reportValidatorExitDelay(
        uint256 _nodeOperatorId,
        uint256 _proofSlotTimestamp,
        bytes calldata _publicKey,
        uint256 _eligibleToExitInSec
    ) external;

    function removeSigningKeysOperatorBH(uint256 _nodeOperatorId, uint256 _fromIndex, uint256 _keysCount) external;

    function setNodeOperatorName(uint256 _nodeOperatorId, string calldata _name) external;

    function invalidateReadyToDepositKeysRange(uint256 _indexFrom, uint256 _indexTo) external;

    function initialize(address _locator, bytes32 _type, uint256 _exitDeadlineThresholdInSeconds) external;

    function onValidatorExitTriggered(
        uint256 _nodeOperatorId,
        bytes calldata _publicKey,
        uint256 _withdrawalRequestPaidFee,
        uint256 _exitType
    ) external;

    function removeSigningKey(uint256 _nodeOperatorId, uint256 _index) external;

    function removeSigningKeys(uint256 _nodeOperatorId, uint256 _fromIndex, uint256 _keysCount) external;

    function deactivateNodeOperator(uint256 _nodeOperatorId) external;

    function addSigningKeysOperatorBH(
        uint256 _nodeOperatorId,
        uint256 _keysCount,
        bytes calldata _publicKeys,
        bytes calldata _signatures
    ) external;

    function addNodeOperator(string calldata _name, address _rewardAddress) external returns (uint256 id);

    function onRewardsMinted(uint256) external;

    function finalizeUpgrade_v4(uint256 _exitDeadlineThresholdInSeconds) external;

    function distributeReward() external;

    function onWithdrawalCredentialsChanged() external;

    function activateNodeOperator(uint256 _nodeOperatorId) external;

    function unsafeUpdateValidatorsCount(uint256 _nodeOperatorId, uint256 _exitedValidatorsCount) external;

    function setNodeOperatorRewardAddress(uint256 _nodeOperatorId, address _rewardAddress) external;

    function updateExitedValidatorsCount(
        bytes calldata _nodeOperatorIds,
        bytes calldata _exitedValidatorsCounts
    ) external;

    function transferToVault(address _token) external;

    function updateTargetValidatorsLimits(
        uint256 _nodeOperatorId,
        bool _isTargetLimitActive,
        uint256 _targetLimit
    ) external;

    function setNodeOperatorStakingLimit(uint256 _nodeOperatorId, uint64 _vettedSigningKeysCount) external;

    function decreaseVettedSigningKeysCount(
        bytes calldata _nodeOperatorIds,
        bytes calldata _vettedSigningKeysCounts
    ) external;

    function setExitDeadlineThreshold(uint256 _threshold, uint256 _lateReportingWindow) external;

    function obtainDepositData(
        uint256 _depositsCount,
        bytes calldata
    ) external returns (bytes memory publicKeys, bytes memory signatures);

    function onExitedAndStuckValidatorsCountsUpdated() external;

    function removeSigningKeyOperatorBH(uint256 _nodeOperatorId, uint256 _index) external;
}
