// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xC69685E89Cefc327b43B7234AC646451B27c544d (OssifiableProxy) → implementation 0xA612E30D71d7D54aEaf4e5A21023F3F270932C2C (OperatorGrid)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IOperatorGrid {
    struct TierParams {
        uint256 shareLimit;
        uint256 reserveRatioBP;
        uint256 forcedRebalanceThresholdBP;
        uint256 infraFeeBP;
        uint256 liquidityFeeBP;
        uint256 reservationFeeBP;
    }

    function alterTiers(uint256[] calldata _tierIds, TierParams[] calldata _tierParams) external;

    function changeTier(address _vault, uint256 _requestedTierId, uint256 _requestedShareLimit) external returns (bool);

    function grantRole(bytes32 role, address account) external;

    function initialize(address _admin, TierParams calldata _defaultTierParams) external;

    function onBurnedShares(address _vault, uint256 _amount) external;

    function onMintedShares(address _vault, uint256 _amount, bool _overrideLimits) external;

    function registerGroup(address _nodeOperator, uint256 _shareLimit) external;

    function registerTiers(address _nodeOperator, TierParams[] calldata _tiers) external;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function resetVaultTier(address _vault) external;

    function revokeRole(bytes32 role, address account) external;

    function setConfirmExpiry(uint256 _newConfirmExpiry) external;

    function setVaultJailStatus(address _vault, bool _isInJail) external;

    function syncTier(address _vault) external returns (bool);

    function updateGroupShareLimit(address _nodeOperator, uint256 _shareLimit) external;

    function updateVaultFees(
        address _vault,
        uint256 _infraFeeBP,
        uint256 _liquidityFeeBP,
        uint256 _reservationFeeBP
    ) external;

    function updateVaultShareLimit(address _vault, uint256 _requestedShareLimit) external returns (bool);
}
