// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x147f8d3cf3004FAf9Bf94E88B54b6C06De507be9 (OracleReportSanityChecker)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IOracleReportSanityChecker {
    struct LimitsList {
        uint256 exitedEthAmountPerDayLimit;
        uint256 appearedEthAmountPerDayLimit;
        uint256 annualBalanceIncreaseBPLimit;
        uint256 simulatedShareRateDeviationBPLimit;
        uint256 maxBalanceExitRequestedPerReportInEth;
        uint256 maxEffectiveBalanceWeightWCType01;
        uint256 maxEffectiveBalanceWeightWCType02;
        uint256 maxItemsPerExtraDataTransaction;
        uint256 maxNodeOperatorsPerExtraDataItem;
        uint256 requestTimestampMargin;
        uint256 maxPositiveTokenRebase;
        uint256 maxCLBalanceDecreaseBP;
        uint256 clBalanceOraclesErrorUpperBPLimit;
        uint256 consolidationEthAmountPerDayLimit;
        uint256 exitedValidatorEthAmountLimit;
        uint256 externalPendingBalanceCapEth;
    }

    function checkAccountingOracleReport(
        uint256 _timeElapsed,
        uint256 _preCLValidatorsBalance,
        uint256 _preCLPendingBalance,
        uint256 _postCLValidatorsBalance,
        uint256 _postCLPendingBalance,
        uint256 _withdrawalVaultBalance,
        uint256 _elRewardsVaultBalance,
        uint256 _sharesRequestedToBurn,
        uint256 _deposits,
        uint256 _withdrawalsVaultTransfer
    ) external;

    function grantRole(bytes32 role, address account) external;

    function migrateBaselineSnapshot() external;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function setAnnualBalanceIncreaseBPLimit(uint256 _annualBalanceIncreaseBPLimit) external;

    function setAppearedEthAmountPerDayLimit(uint256 _appearedEthAmountPerDayLimit) external;

    function setConsolidationEthAmountPerDayLimit(uint256 _consolidationEthAmountPerDayLimit) external;

    function setExitedEthAmountPerDayLimit(uint256 _exitedEthAmountPerDayLimit) external;

    function setExitedValidatorEthAmountLimit(uint256 _exitedValidatorEthAmountLimit) external;

    function setExternalPendingBalanceCapEth(uint256 _externalPendingBalanceCapEth) external;

    function setMaxBalanceExitRequestedPerReportInEth(uint256 _maxBalanceExitRequestedPerReportInEth) external;

    function setMaxCLBalanceDecreaseBP(uint256 _maxCLBalanceDecreaseBP) external;

    function setMaxEffectiveBalanceWeightWCType01(uint256 _maxEffectiveBalanceWeightWCType01) external;

    function setMaxEffectiveBalanceWeightWCType02(uint256 _maxEffectiveBalanceWeightWCType02) external;

    function setMaxItemsPerExtraDataTransaction(uint256 _maxItemsPerExtraDataTransaction) external;

    function setMaxNodeOperatorsPerExtraDataItem(uint256 _maxNodeOperatorsPerExtraDataItem) external;

    function setMaxPositiveTokenRebase(uint256 _maxPositiveTokenRebase) external;

    function setOracleReportLimits(LimitsList calldata _limitsList, address _secondOpinionOracle) external;

    function setRequestTimestampMargin(uint256 _requestTimestampMargin) external;

    function setSecondOpinionOracleAndCLBalanceUpperMargin(
        address _secondOpinionOracle,
        uint256 _clBalanceOraclesErrorUpperBPLimit
    ) external;

    function setSimulatedShareRateDeviationBPLimit(uint256 _simulatedShareRateDeviationBPLimit) external;
}
