// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xbf05A929c3D7885a6aeAd833a992dA6E5ac23b09 (OracleDaemonConfig)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IOracleDaemonConfig {
    function grantRole(bytes32 role, address account) external;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;

    function set(string calldata _key, bytes calldata _value) external;

    function unset(string calldata _key) external;

    function update(string calldata _key, bytes calldata _value) external;
}
