// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x79ef3a538200Fe4981D67E7e886bfb36D4Cb5a31 (OracleRouter)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IOracleRouter {
    function setEmergencyOperator(address emergencyOperator_) external;

    function setEthUsdBridge(uint32 maxStalenessSeconds_) external;

    function setManager(address manager_) external;

    function setTokenActive(address token_, bool isActive_) external;

    function setTokenEthUsdStalenessOverride(address token_, uint32 overrideSeconds_) external;

    function setTokenFeed(address token_, uint8 primaryQuote_, uint32 maxStalenessSeconds_, bool isActive_) external;

    function syncEthUsdBridge() external;

    function syncTokenFeed(address token_) external;
}
