// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xC1d0b3DE6792Bf6b4b37EccdcC24e45978Cfd2Eb (OssifiableProxy), proxy ABI
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IOssifiableProxy {
    function proxy__changeAdmin(address newAdmin_) external;

    function proxy__ossify() external;

    function proxy__upgradeTo(address newImplementation_) external;

    function proxy__upgradeToAndCall(
        address newImplementation_,
        bytes calldata setupCalldata_,
        bool forceCall_
    ) external;
}
