// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xF4bF42c6D6A0E38825785048124DBAD6c9eaaac3 (OssifiableProxy) → implementation 0xE78717192C45736DF0E4be55c0219Ee7f9aDdd0D (PredepositGuarantee)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IPredepositGuarantee {
    struct Deposit {
        bytes pubkey;
        bytes signature;
        uint256 amount;
        bytes32 depositDataRoot;
    }

    struct Fp {
        bytes32 a;
        bytes32 b;
    }

    struct Fp2 {
        bytes32 c0_a;
        bytes32 c0_b;
        bytes32 c1_a;
        bytes32 c1_b;
    }

    struct DepositY {
        Fp pubkeyY;
        Fp2 signatureY;
    }

    struct ValidatorWitness {
        bytes32[] proof;
        bytes pubkey;
        uint256 validatorIndex;
        uint64 childBlockTimestamp;
        uint64 slot;
        uint64 proposerIndex;
    }

    struct ValidatorTopUp {
        bytes pubkey;
        uint256 amount;
    }

    function activateValidator(bytes calldata _pubkey) external;

    function claimGuarantorRefund(address _recipient) external returns (uint256 claimedEther);

    function grantRole(bytes32 role, address account) external;

    function initialize(address _defaultAdmin) external;

    function pauseFor(uint256 _duration) external;

    function pauseUntil(uint256 _pauseUntilInclusive) external;

    function predeposit(
        address _stakingVault,
        Deposit[] calldata _deposits,
        DepositY[] calldata _depositsY
    ) external payable;

    function proveInvalidValidatorWC(ValidatorWitness calldata _witness, bytes32 _invalidWithdrawalCredentials) external;

    function proveUnknownValidator(ValidatorWitness calldata _witness, address _stakingVault) external;

    function proveWCActivateAndTopUpValidators(
        ValidatorWitness[] calldata _witnesses,
        uint256[] calldata _amounts
    ) external;

    function proveWCAndActivate(ValidatorWitness calldata _witness) external;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function setNodeOperatorDepositor(address _newDepositor) external;

    function setNodeOperatorGuarantor(address _newGuarantor) external;

    function topUpExistingValidators(ValidatorTopUp[] calldata _topUps) external;

    function topUpNodeOperatorBalance(address _nodeOperator) external payable;

    function withdrawNodeOperatorBalance(address _nodeOperator, uint256 _amount, address _recipient) external;
}
