// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, hoodi 0x68009122a394504E8fD7fee58F92Cd73c6A60717 (SetDepositsReserveTarget)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ISetDepositsReserveTarget {}
