// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xFdDf38947aFB03C621C71b06C9C70bce73f12999 (OssifiableProxy) → implementation 0xdd76927045435c7605cf6f5f978cfb8cabdb5f80 (StakingRouter)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IStakingRouter {
    struct StakingModuleConfig {
        uint256 stakeShareLimit;
        uint256 priorityExitShareThreshold;
        uint256 stakingModuleFee;
        uint256 treasuryFee;
        uint256 maxDepositsPerBlock;
        uint256 minDepositBlockDistance;
        uint256 withdrawalCredentialsType;
    }

    struct ValidatorExitData {
        uint256 stakingModuleId;
        uint256 nodeOperatorId;
        bytes pubkey;
    }

    struct ValidatorsCountsCorrection {
        uint256 currentModuleExitedValidatorsCount;
        uint256 currentNodeOperatorExitedValidatorsCount;
        uint256 newModuleExitedValidatorsCount;
        uint256 newNodeOperatorExitedValidatorsCount;
    }

    function addStakingModule(
        string calldata _name,
        address _stakingModuleAddress,
        StakingModuleConfig calldata _stakingModuleConfig
    ) external;

    function decreaseStakingModuleVettedKeysCountByNodeOperator(
        uint256 _stakingModuleId,
        bytes calldata _nodeOperatorIds,
        bytes calldata _vettedSigningKeysCounts
    ) external;

    function deposit(uint256 _stakingModuleId, bytes calldata _depositCalldata) external;

    function finalizeUpgrade_v4(uint256 _maxTopUpPerBlockGwei) external;

    function grantRole(bytes32 role, address account) external;

    function initialize(address _admin, bytes32 _withdrawalCredentials, uint256 _maxTopUpPerBlockGwei) external;

    function onValidatorExitTriggered(
        ValidatorExitData[] calldata validatorExitData,
        uint256 _withdrawalRequestPaidFee,
        uint256 _exitType
    ) external;

    function onValidatorsCountsByNodeOperatorReportingFinished() external;

    function receiveDepositableEther() external payable;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function reportRewardsMinted(uint256[] calldata _stakingModuleIds, uint256[] calldata _totalShares) external;

    function reportStakingModuleExitedValidatorsCountByNodeOperator(
        uint256 _stakingModuleId,
        bytes calldata _nodeOperatorIds,
        bytes calldata _exitedValidatorsCounts
    ) external;

    function reportValidatorBalancesByStakingModule(
        uint256[] calldata _stakingModuleIds,
        uint256[] calldata _validatorBalancesGwei
    ) external;

    function reportValidatorExitDelay(
        uint256 _stakingModuleId,
        uint256 _nodeOperatorId,
        uint256 _proofSlotTimestamp,
        bytes calldata _publicKey,
        uint256 _eligibleToExitInSec
    ) external;

    function revokeRole(bytes32 role, address account) external;

    function setMaxTopUpPerBlockGwei(uint256 _newValue) external;

    function setStakingModuleStatus(uint256 _stakingModuleId, uint8 _status) external;

    function setWithdrawalCredentials(bytes32 _withdrawalCredentials) external;

    function topUp(
        uint256 _stakingModuleId,
        uint256[] calldata _keyIndices,
        uint256[] calldata _operatorIds,
        bytes[] calldata _pubkeys,
        uint256[] calldata _topUpLimits
    ) external;

    function unsafeSetExitedValidatorsCount(
        uint256 _stakingModuleId,
        uint256 _nodeOperatorId,
        bool _triggerUpdateFinish,
        ValidatorsCountsCorrection calldata _correction
    ) external;

    function updateAllStakingModulesFees(
        uint256[] calldata _stakingModuleFees,
        uint256[] calldata _treasuryFees
    ) external;

    function updateExitedValidatorsCountByStakingModule(
        uint256[] calldata _stakingModuleIds,
        uint256[] calldata _exitedValidatorsCounts
    ) external returns (uint256);

    function updateModuleShares(
        uint256 _stakingModuleId,
        uint16 _stakeShareLimit,
        uint16 _priorityExitShareThreshold
    ) external;

    function updateStakingModule(
        uint256 _stakingModuleId,
        uint256 _stakeShareLimit,
        uint256 _priorityExitShareThreshold,
        uint256 _stakingModuleFee,
        uint256 _treasuryFee,
        uint256 _maxDepositsPerBlock,
        uint256 _minDepositBlockDistance
    ) external;

    function updateTargetValidatorsLimits(
        uint256 _stakingModuleId,
        uint256 _nodeOperatorId,
        uint256 _targetLimitMode,
        uint256 _targetLimit
    ) external;
}
