// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x2a30F5aC03187674553024296bed35Aa49749DDa (TimeConstraints)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ITimeConstraints {
    function checkTimeAfterTimestampAndEmit(uint40 timestamp) external;

    function checkTimeBeforeTimestampAndEmit(uint40 timestamp) external;

    function checkTimeWithinDayTimeAndEmit(uint32 startDayTime, uint32 endDayTime) external;
}
