// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xf73a1260d222f447210581DDf212D915c09a3249 (AppProxyUpgradeable) → implementation 0xde3A93028F2283cc28756B3674BD657eaFB992f4 (TokenManager)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ITokenManager {
    function assignVested(
        address _receiver,
        uint256 _amount,
        uint64 _start,
        uint64 _cliff,
        uint64 _vested,
        bool _revokable
    ) external returns (uint256);

    function mint(address _receiver, uint256 _amount) external;

    function onTransfer(address _from, address _to, uint256 _amount) external returns (bool);

    function transferToVault(address _token) external;

    function burn(address _holder, uint256 _amount) external;

    function assign(address _receiver, uint256 _amount) external;

    function issue(uint256 _amount) external;

    function forward(bytes calldata _evmScript) external;

    function onApprove(address, address, uint256) external returns (bool);

    function initialize(address _token, bool _transferable, uint256 _maxAccountTokens) external;

    function proxyPayment(address) external payable returns (bool);

    function revokeVesting(address _holder, uint256 _vestingId) external;
}
