// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x3FC2C71579D80790Aaa3fc7Be8B66ac39dC57374 (OssifiableProxy) → implementation 0xb08dBc68C521cD7A4318dc4C807a42bEB20f1106 (TopUpGateway)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ITopUpGateway {
    struct BeaconRootData {
        uint64 childBlockTimestamp;
        uint64 slot;
        uint64 proposerIndex;
    }

    struct ValidatorWitness {
        bytes32[] proofValidator;
        bytes pubkey;
        uint64 effectiveBalance;
        uint64 activationEligibilityEpoch;
        uint64 activationEpoch;
        uint64 exitEpoch;
        uint64 withdrawableEpoch;
        bool slashed;
    }

    struct TopUpData {
        uint256 moduleId;
        uint256[] keyIndices;
        uint256[] operatorIds;
        uint256[] validatorIndices;
        BeaconRootData beaconRootData;
        ValidatorWitness[] validatorWitness;
        uint256[] pendingBalanceGwei;
    }

    function grantRole(bytes32 role, address account) external;

    function initialize(
        address _admin,
        uint256 _maxValidatorsPerTopUp,
        uint256 _minTopUpBlockDistance,
        uint256 _maxRootAgeSec,
        uint256 _targetBalanceGwei,
        uint256 _minTopUpGwei
    ) external;

    function pauseFor(uint256 _duration) external;

    function pauseUntil(uint256 _pauseUntilInclusive) external;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function setMaxRootAge(uint256 _newValue) external;

    function setMaxValidatorsPerTopUp(uint256 _newValue) external;

    function setMinBlockDistance(uint256 _newValue) external;

    function setTopUpBalanceLimits(uint256 _targetBalanceGwei, uint256 _minTopUpGwei) external;

    function topUp(TopUpData calldata _topUps) external;
}
