// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0xDC00116a0D3E064427dA2600449cfD2566B3037B (TriggerableWithdrawalsGateway)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface ITriggerableWithdrawalsGateway {
    struct ValidatorExitData {
        uint256 stakingModuleId;
        uint256 nodeOperatorId;
        bytes pubkey;
    }

    function grantRole(bytes32 role, address account) external;

    function pauseFor(uint256 _duration) external;

    function pauseUntil(uint256 _pauseUntilInclusive) external;

    function renounceRole(bytes32 role, address account) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function setExitRequestLimit(
        uint256 maxExitRequestsLimit,
        uint256 exitsPerFrame,
        uint256 frameDurationInSec
    ) external;

    function triggerFullWithdrawals(
        ValidatorExitData[] calldata validatorsData,
        address refundRecipient,
        uint256 exitType
    ) external payable;
}
