// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x0De4Ea0184c2ad0BacA7183356Aea5B8d5Bf5c6e (OssifiableProxy) → implementation 0x2C3386b39db89eef0F362A3BE0C05a6811E809E3 (ValidatorsExitBusOracle)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IValidatorsExitBusOracle {
    struct ExitRequestsData {
        bytes data;
        uint256 dataFormat;
    }

    struct ReportData {
        uint256 consensusVersion;
        uint256 refSlot;
        uint256 requestsCount;
        uint256 dataFormat;
        bytes data;
    }

    function discardConsensusReport(uint256 refSlot) external;

    function finalizeUpgrade_v3(
        uint256 maxValidatorsPerReport,
        uint256 maxExitBalanceEth,
        uint256 balancePerFrameEth,
        uint256 frameDurationInSec,
        uint256 consensusVersion
    ) external;

    function grantRole(bytes32 role, address account) external;

    function initialize(
        address admin,
        address consensusContract,
        uint256 consensusVersion,
        uint256 lastProcessingRefSlot,
        uint256 maxValidatorsPerReport,
        uint256 maxExitBalanceEth,
        uint256 balancePerFrameEth,
        uint256 frameDurationInSec
    ) external;

    function pauseFor(uint256 _duration) external;

    function pauseUntil(uint256 _pauseUntilInclusive) external;

    function renounceRole(bytes32 role, address account) external;

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function setConsensusContract(address addr) external;

    function setConsensusVersion(uint256 version) external;

    function setExitRequestLimit(
        uint256 maxExitBalanceEth,
        uint256 balancePerFrameEth,
        uint256 frameDurationInSec
    ) external;

    function setMaxValidatorsPerReport(uint256 maxRequests) external;

    function submitConsensusReport(bytes32 reportHash, uint256 refSlot, uint256 deadline) external;

    function submitExitRequestsData(ExitRequestsData calldata request) external;

    function submitExitRequestsHash(bytes32 exitRequestsHash) external;

    function submitReportData(ReportData calldata data, uint256 contractVersion) external;

    function triggerExits(
        ExitRequestsData calldata exitsData,
        uint256[] calldata exitDataIndexes,
        address refundRecipient
    ) external payable;
}
