// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x1d201BE093d847f6446530Efb0E8Fb426d176709 (OssifiableProxy) → implementation 0x6330fE7756FBE8649adfb9A541d61C5edB8B4D70 (VaultHub)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IVaultHub {
    struct ValidatorWitness {
        bytes32[] proof;
        bytes pubkey;
        uint256 validatorIndex;
        uint64 childBlockTimestamp;
        uint64 slot;
        uint64 proposerIndex;
    }

    function applyVaultReport(
        address _vault,
        uint256 _reportTimestamp,
        uint256 _reportTotalValue,
        int256 _reportInOutDelta,
        uint256 _reportCumulativeLidoFees,
        uint256 _reportLiabilityShares,
        uint256 _reportMaxLiabilityShares,
        uint256 _reportSlashingReserve
    ) external;

    function burnShares(address _vault, uint256 _amountOfShares) external;

    function collectERC20FromVault(address _vault, address _token, address _recipient, uint256 _amount) external;

    function connectVault(address _vault) external;

    function decreaseInternalizedBadDebt(uint256 _amountOfShares) external;

    function disconnect(address _vault) external;

    function forceRebalance(address _vault) external;

    function forceValidatorExit(address _vault, bytes calldata _pubkeys, address _refundRecipient) external payable;

    function fund(address _vault) external payable;

    function grantRole(bytes32 role, address account) external;

    function initialize(address _admin) external;

    function internalizeBadDebt(address _badDebtVault, uint256 _maxSharesToInternalize) external returns (uint256);

    function mintShares(address _vault, address _recipient, uint256 _amountOfShares) external;

    function pauseBeaconChainDeposits(address _vault) external;

    function pauseFor(uint256 _duration) external;

    function pauseUntil(uint256 _pauseUntilInclusive) external;

    function proveUnknownValidatorToPDG(address _vault, ValidatorWitness calldata _witness) external;

    function rebalance(address _vault, uint256 _shares) external;

    function renounceRole(bytes32 role, address callerConfirmation) external;

    function requestValidatorExit(address _vault, bytes calldata _pubkeys) external;

    function resume() external;

    function resumeBeaconChainDeposits(address _vault) external;

    function revokeRole(bytes32 role, address account) external;

    function setLiabilitySharesTarget(address _vault, uint256 _liabilitySharesTarget) external;

    function settleLidoFees(address _vault) external;

    function socializeBadDebt(
        address _badDebtVault,
        address _vaultAcceptor,
        uint256 _maxSharesToSocialize
    ) external returns (uint256);

    function transferAndBurnShares(address _vault, uint256 _amountOfShares) external;

    function transferVaultOwnership(address _vault, address _newOwner) external;

    function triggerValidatorWithdrawals(
        address _vault,
        bytes calldata _pubkeys,
        uint64[] calldata _amountsInGwei,
        address _refundRecipient
    ) external payable;

    function updateConnection(
        address _vault,
        uint256 _shareLimit,
        uint256 _reserveRatioBP,
        uint256 _forcedRebalanceThresholdBP,
        uint256 _infraFeeBP,
        uint256 _liquidityFeeBP,
        uint256 _reservationFeeBP
    ) external;

    function voluntaryDisconnect(address _vault) external;

    function withdraw(address _vault, address _recipient, uint256 _ether) external;
}
