// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x28F9Ac198C4E0FA6A9Ad2c2f97CB38F1A3120f27 (VaultsAdapter)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IVaultsAdapter {
    function forceValidatorExit(address _vault, bytes calldata _pubkeys) external;

    function setLiabilitySharesTarget(address _vault, uint256 _liabilitySharesTarget) external;

    function setValidatorExitFeeLimit(uint256 _validatorExitFeeLimit) external;

    function setVaultJailStatus(address _vault, bool _isInJail) external;

    function socializeBadDebt(address _badDebtVault, address _vaultAcceptor, uint256 _maxSharesToSocialize) external;

    function updateVaultFees(
        address _vault,
        uint256 _infraFeeBP,
        uint256 _liquidityFeeBP,
        uint256 _reservationFeeBP
    ) external;

    function withdrawETH(address _recipient) external;
}
