// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x889edC2eDab5f40e902b864aD4d7AdE8E412F9B1 (OssifiableProxy) → implementation 0xE42C659Dc09109566720EA8b2De186c2Be7D94D9 (WithdrawalQueueERC721)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IWithdrawalQueue {
    struct PermitInput {
        uint256 value;
        uint256 deadline;
        uint8 v;
        bytes32 r;
        bytes32 s;
    }

    function approve(address _to, uint256 _requestId) external;

    function claimWithdrawal(uint256 _requestId) external;

    function claimWithdrawals(uint256[] calldata _requestIds, uint256[] calldata _hints) external;

    function claimWithdrawalsTo(uint256[] calldata _requestIds, uint256[] calldata _hints, address _recipient) external;

    function finalize(uint256 _lastRequestIdToBeFinalized, uint256 _maxShareRate) external payable;

    function grantRole(bytes32 role, address account) external;

    function initialize(address _admin) external;

    function onOracleReport(
        bool _isBunkerModeNow,
        uint256 _bunkerStartTimestamp,
        uint256 _currentReportTimestamp
    ) external;

    function pauseFor(uint256 _duration) external;

    function pauseUntil(uint256 _pauseUntilInclusive) external;

    function renounceRole(bytes32 role, address account) external;

    function requestWithdrawals(
        uint256[] calldata _amounts,
        address _owner
    ) external returns (uint256[] memory requestIds);

    function requestWithdrawalsWithPermit(
        uint256[] calldata _amounts,
        address _owner,
        PermitInput calldata _permit
    ) external returns (uint256[] memory requestIds);

    function requestWithdrawalsWstETH(
        uint256[] calldata _amounts,
        address _owner
    ) external returns (uint256[] memory requestIds);

    function requestWithdrawalsWstETHWithPermit(
        uint256[] calldata _amounts,
        address _owner,
        PermitInput calldata _permit
    ) external returns (uint256[] memory requestIds);

    function resume() external;

    function revokeRole(bytes32 role, address account) external;

    function safeTransferFrom(address _from, address _to, uint256 _requestId) external;

    function safeTransferFrom(address _from, address _to, uint256 _requestId, bytes calldata _data) external;

    function setApprovalForAll(address _operator, bool _approved) external;

    function setBaseURI(string calldata _baseURI) external;

    function setNFTDescriptorAddress(address _nftDescriptorAddress) external;

    function transferFrom(address _from, address _to, uint256 _requestId) external;
}
