// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

/// @notice Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
/// @dev Source: Etherscan, mainnet 0x41527B2d03844dB6b0945f25702cB958b6d55989 (OssifiableProxy) → implementation 0x43a66B32c9AdcA1A59b273E69b61Da5197c21cCd (L1ERC20Bridge)
///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript
///      test reads state through the matching `abi/*.abi.ts` module. Enums are declared as
///      their storage type (`uint8`): the ABI carries no member names.
interface IZkSyncL1ERC20Bridge {
    struct InitializeAddressesParams {
        address _l1Token;
        address _l2Token;
        address _governor;
        address _admin;
        address _zkSync;
    }

    function claimFailedDeposit(
        address _depositSender,
        address _l1Token,
        bytes32 _l2TxHash,
        uint256 _l2BlockNumber,
        uint256 _l2MessageIndex,
        uint16 _l2TxNumberInBlock,
        bytes32[] calldata _merkleProof
    ) external;

    function deposit(
        address _l2Receiver,
        address _l1Token,
        uint256 _amount,
        uint256 _l2TxGasLimit,
        uint256 _l2TxGasPerPubdataByte
    ) external payable returns (bytes32 l2TxHash);

    function deposit(
        address _l2Receiver,
        address _l1Token,
        uint256 _amount,
        uint256 _l2TxGasLimit,
        uint256 _l2TxGasPerPubdataByte,
        address _refundRecipient
    ) external payable returns (bytes32 l2TxHash);

    function disableDeposits() external;

    function disableWithdrawals() external;

    function enableDeposits() external;

    function enableWithdrawals() external;

    function finalizeWithdrawal(
        uint256 _l2BlockNumber,
        uint256 _l2MessageIndex,
        uint16 _l2TxNumberInBlock,
        bytes calldata _message,
        bytes32[] calldata _merkleProof
    ) external;

    function grantRole(bytes32 role, address account) external;

    function initialize(
        bytes[] calldata _factoryDeps,
        InitializeAddressesParams calldata addresses,
        uint256 _deployBridgeImplementationFee,
        uint256 _deployBridgeProxyFee
    ) external payable;

    function renounceRole(bytes32 role, address account) external;

    function revokeRole(bytes32 role, address account) external;
}
