import path from "node:path";
import prettier from "prettier";
import { Abi } from "abitype";

export interface AbiTsHeader {
  contractName: string;
  source: string;
}

export async function renderAbiTs(exportName: string, abi: Abi, header: AbiTsHeader): Promise<string> {
  const code = [
    `// Generated by \`npm run abi:sync\` — do not edit by hand, re-run the command instead.`,
    `// Contract: ${header.contractName}`,
    `// Source: ${header.source}`,
    ``,
    `export const ${exportName}_ABI = ${JSON.stringify(abi)} as const;`,
    ``,
  ].join("\n");

  const options = (await prettier.resolveConfig(path.resolve("package.json"))) ?? {};
  return prettier.format(code, { ...options, parser: "typescript" });
}
