import { Abi, AbiFunction, AbiParameter } from "abitype";

export const SOLIDITY_VERSION = "0.8.26";

export interface SolInterfaceOptions {
  /** Default — every state-changing method. */
  methods?: string[];
  source: string;
}

interface StructDefinition {
  name: string;
  fields: string[];
  dependencies: string[];
}

type AbiParameterWithComponents = AbiParameter & { components?: readonly AbiParameter[] };

const REFERENCE_TYPE_PATTERN = /(\[\d*\]$)|^(bytes|string|tuple)$/;

/**
 * Only state-changing methods are declared: an omnibus calls them, while view methods are read
 * by the TypeScript test through `abi/*.abi.ts`. Keeps the interface reviewable at a glance.
 * The output is valid Solidity; `syncAbi` runs it through `forge fmt` before writing.
 */
export function renderSolInterface(interfaceName: string, abi: Abi, options: SolInterfaceOptions): string {
  const functions = selectFunctions(abi, options.methods);
  const structs = new Map<string, StructDefinition>();

  const functionLines = functions.map((fn) => renderFunction(fn, structs));
  const structLines = orderStructs(structs).map(renderStruct);

  return [
    `// SPDX-License-Identifier: MIT`,
    `pragma solidity ${SOLIDITY_VERSION};`,
    ``,
    `/// @notice Generated by \`npm run abi:sync\` — do not edit by hand, re-run the command instead.`,
    `/// @dev Source: ${options.source}`,
    `///      Only state-changing methods are declared: an omnibus calls them, while the TypeScript`,
    `///      test reads state through the matching \`abi/*.abi.ts\` module. Enums are declared as`,
    `///      their storage type (\`uint8\`): the ABI carries no member names.`,
    `interface ${interfaceName} {`,
    [...structLines, ...functionLines].join("\n\n"),
    `}`,
    ``,
  ].join("\n");
}

function selectFunctions(abi: Abi, methods?: string[]): AbiFunction[] {
  const stateChanging = abi.filter(
    (item): item is AbiFunction =>
      item.type === "function" && (item.stateMutability === "nonpayable" || item.stateMutability === "payable"),
  );

  if (!methods) {
    return stateChanging;
  }

  const available = new Set(stateChanging.map((fn) => fn.name));
  const missing = methods.filter((method) => !available.has(method));
  if (missing.length > 0) {
    throw new Error(
      `Methods not found among state-changing functions of the ABI: ${missing.join(", ")}.\n` +
        `Available: ${[...available].sort().join(", ")}`,
    );
  }

  const requested = new Set(methods);
  return stateChanging.filter((fn) => requested.has(fn.name));
}

function renderFunction(fn: AbiFunction, structs: Map<string, StructDefinition>): string {
  const inputs = fn.inputs.map((input) => renderParameter(input, "calldata", structs)).join(", ");
  const outputs = fn.outputs.map((output) => renderParameter(output, "memory", structs)).join(", ");
  const mutability = fn.stateMutability === "payable" ? " payable" : "";
  const returns = outputs.length > 0 ? ` returns (${outputs})` : "";
  return `    function ${fn.name}(${inputs}) external${mutability}${returns};`;
}

function renderParameter(
  parameter: AbiParameterWithComponents,
  location: "calldata" | "memory",
  structs: Map<string, StructDefinition>,
): string {
  const type = resolveType(parameter, structs);
  const dataLocation = REFERENCE_TYPE_PATTERN.test(parameter.type) ? ` ${location}` : "";
  const name = parameter.name ? ` ${parameter.name}` : "";
  return `${type}${dataLocation}${name}`;
}

function renderStructField(field: AbiParameterWithComponents, structs: Map<string, StructDefinition>): string {
  if (!field.name) {
    throw new Error(`Struct field of type "${field.type}" has no name`);
  }
  return `${resolveType(field, structs)} ${field.name}`;
}

/** Tuples become structs declared in the interface; enums keep their storage type (ABI has no member names). */
function resolveType(parameter: AbiParameterWithComponents, structs: Map<string, StructDefinition>): string {
  const bracketIndex = parameter.type.indexOf("[");
  const baseType = bracketIndex === -1 ? parameter.type : parameter.type.slice(0, bracketIndex);
  const suffix = bracketIndex === -1 ? "" : parameter.type.slice(bracketIndex);

  if (baseType !== "tuple") {
    return `${baseType}${suffix}`;
  }

  const structName = parseStructName(parameter);
  registerStruct(structName, parameter.components ?? [], structs);
  return `${structName}${suffix}`;
}

function parseStructName(parameter: AbiParameterWithComponents): string {
  const match = /^struct (?:\w+\.)?(\w+)/.exec(parameter.internalType ?? "");
  if (!match) {
    throw new Error(
      `Tuple parameter "${parameter.name}" has no struct name in internalType ("${parameter.internalType}")`,
    );
  }
  return match[1];
}

function registerStruct(name: string, components: readonly AbiParameter[], structs: Map<string, StructDefinition>) {
  const dependencies: string[] = [];
  const fields = components.map((component) => {
    const field = renderStructField(component, structs);
    if (component.type.startsWith("tuple")) {
      dependencies.push(parseStructName(component));
    }
    return field;
  });

  const existing = structs.get(name);
  if (existing) {
    if (existing.fields.join(";") !== fields.join(";")) {
      throw new Error(`Two different structs named "${name}" found in the ABI — cannot render a single interface`);
    }
    return;
  }
  structs.set(name, { name, fields, dependencies });
}

function orderStructs(structs: Map<string, StructDefinition>): StructDefinition[] {
  const ordered: StructDefinition[] = [];
  const visited = new Set<string>();

  const visit = (definition: StructDefinition) => {
    if (visited.has(definition.name)) {
      return;
    }
    visited.add(definition.name);
    for (const dependency of definition.dependencies) {
      const dependencyDefinition = structs.get(dependency);
      if (dependencyDefinition) {
        visit(dependencyDefinition);
      }
    }
    ordered.push(definition);
  };

  for (const definition of structs.values()) {
    visit(definition);
  }
  return ordered;
}

function renderStruct(definition: StructDefinition): string {
  return [`    struct ${definition.name} {`, ...definition.fields.map((field) => `        ${field};`), `    }`].join(
    "\n",
  );
}
