/*
This file was autogenerated using the following typescript snippet:

function generateOverloadedN(n: number) {
  const overloads: string[] = [];
  const genericTypes: string[] = [];

  for (let i = 1; i <= n; ++i) {
    genericTypes.push(`O${i} extends any[], R${i} extends any`);
    overloads.push(`  (...args: O${i}): R${i};`);
  }
  return `interface Overloaded${n}<${genericTypes.join(", ")}> {\n${overloads.join("\n")}\n}\n`
}

function generateTuplesToRecord(n: number) {
  const genericTypes: string[] = []
  const typeInferences: string[] = []
  for (let i = 1; i <= n; ++i) {
    genericTypes.push(`A${i}`, `R${i}`)
    typeInferences.push(`  (A${i} extends [string, ...any] ? { [K in A${i}[0]]: R${i} }: {})`)
  }
  return `type TuplesToRecord${n}<${genericTypes.join(", ")}> =\n${typeInferences.join(" &\n")}\n;\n`
}

function generateOverloadedInputResultMap(n: number) {
  const ternaryCheck: string[] = [];
  const inferTypes: string[] = [];
  const typesToRecords: string[] = []
  for (let i = 1; i <= n; ++i) {
    inferTypes.push(`infer A${i}`, `infer R${i}`)
    ternaryCheck.push(`T extends Overloaded${i}<${inferTypes.join(", ")}>`)
    typesToRecords.push(`TuplesToRecord${i}<${inferTypes.join(", ").replace(/infer /g, "")}>`)
  }
  let res = "export type OverloadedInputResultMap<T> =\n"
  for (let i = n - 1; i >= 0; --i) {
    res += `${ternaryCheck[i]}\n? ${typesToRecords[i]}\n: `
  }
  res += "never;\n"
  return res
}

function generateOverloadedTypesHelperFile(n: number) {
  let res = ""
  for(let i = 1; i <= n; ++i) {
    res += generateOverloadedN(i);
    res += generateTuplesToRecord(i)
  }
  return res + generateOverloadedInputResultMap(n)
}

console.log(generateOverloadedTypesHelperFile(24))

This helper methods are required to overcome the current limitations of the ReturnType implementation:
    https://stackoverflow.com/questions/52760509/typescript-returntype-of-overloaded-function

The current version supports only 24 overloads of the method.
*/

interface Overloaded1<O1 extends any[], R1 extends any> {
  (...args: O1): R1
}
type TuplesToRecord1<A1, R1> = A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}
interface Overloaded2<O1 extends any[], R1 extends any, O2 extends any[], R2 extends any> {
  (...args: O1): R1
  (...args: O2): R2
}
type TuplesToRecord2<A1, R1, A2, R2> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {})
interface Overloaded3<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
}
type TuplesToRecord3<A1, R1, A2, R2, A3, R3> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {})
interface Overloaded4<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
}
type TuplesToRecord4<A1, R1, A2, R2, A3, R3, A4, R4> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {})
interface Overloaded5<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
}
type TuplesToRecord5<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5> = (A1 extends [string, ...any]
  ? { [K in A1[0]]: R1 }
  : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {})
interface Overloaded6<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
}
type TuplesToRecord6<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6> = (A1 extends [string, ...any]
  ? { [K in A1[0]]: R1 }
  : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {})
interface Overloaded7<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
}
type TuplesToRecord7<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7> = (A1 extends [string, ...any]
  ? { [K in A1[0]]: R1 }
  : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {})
interface Overloaded8<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
}
type TuplesToRecord8<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7, A8, R8> = (A1 extends [string, ...any]
  ? { [K in A1[0]]: R1 }
  : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {})
interface Overloaded9<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
}
type TuplesToRecord9<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7, A8, R8, A9, R9> = (A1 extends [
  string,
  ...any,
]
  ? { [K in A1[0]]: R1 }
  : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {})
interface Overloaded10<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
}
type TuplesToRecord10<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7, A8, R8, A9, R9, A10, R10> = (A1 extends [
  string,
  ...any,
]
  ? { [K in A1[0]]: R1 }
  : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {})
interface Overloaded11<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
}
type TuplesToRecord11<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7, A8, R8, A9, R9, A10, R10, A11, R11> =
  (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
    (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
    (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
    (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
    (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
    (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
    (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
    (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
    (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
    (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
    (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {})
interface Overloaded12<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
}
type TuplesToRecord12<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {})
interface Overloaded13<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
}
type TuplesToRecord13<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {})
interface Overloaded14<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
}
type TuplesToRecord14<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {})
interface Overloaded15<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
}
type TuplesToRecord15<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {})
interface Overloaded16<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
}
type TuplesToRecord16<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {})
interface Overloaded17<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
}
type TuplesToRecord17<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {})
interface Overloaded18<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
}
type TuplesToRecord18<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {})
interface Overloaded19<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
  O19 extends any[],
  R19 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
  (...args: O19): R19
}
type TuplesToRecord19<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
  A19,
  R19,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {}) &
  (A19 extends [string, ...any] ? { [K in A19[0]]: R19 } : {})
interface Overloaded20<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
  O19 extends any[],
  R19 extends any,
  O20 extends any[],
  R20 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
  (...args: O19): R19
  (...args: O20): R20
}
type TuplesToRecord20<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
  A19,
  R19,
  A20,
  R20,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {}) &
  (A19 extends [string, ...any] ? { [K in A19[0]]: R19 } : {}) &
  (A20 extends [string, ...any] ? { [K in A20[0]]: R20 } : {})
interface Overloaded21<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
  O19 extends any[],
  R19 extends any,
  O20 extends any[],
  R20 extends any,
  O21 extends any[],
  R21 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
  (...args: O19): R19
  (...args: O20): R20
  (...args: O21): R21
}
type TuplesToRecord21<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
  A19,
  R19,
  A20,
  R20,
  A21,
  R21,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {}) &
  (A19 extends [string, ...any] ? { [K in A19[0]]: R19 } : {}) &
  (A20 extends [string, ...any] ? { [K in A20[0]]: R20 } : {}) &
  (A21 extends [string, ...any] ? { [K in A21[0]]: R21 } : {})
interface Overloaded22<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
  O19 extends any[],
  R19 extends any,
  O20 extends any[],
  R20 extends any,
  O21 extends any[],
  R21 extends any,
  O22 extends any[],
  R22 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
  (...args: O19): R19
  (...args: O20): R20
  (...args: O21): R21
  (...args: O22): R22
}
type TuplesToRecord22<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
  A19,
  R19,
  A20,
  R20,
  A21,
  R21,
  A22,
  R22,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {}) &
  (A19 extends [string, ...any] ? { [K in A19[0]]: R19 } : {}) &
  (A20 extends [string, ...any] ? { [K in A20[0]]: R20 } : {}) &
  (A21 extends [string, ...any] ? { [K in A21[0]]: R21 } : {}) &
  (A22 extends [string, ...any] ? { [K in A22[0]]: R22 } : {})
interface Overloaded23<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
  O19 extends any[],
  R19 extends any,
  O20 extends any[],
  R20 extends any,
  O21 extends any[],
  R21 extends any,
  O22 extends any[],
  R22 extends any,
  O23 extends any[],
  R23 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
  (...args: O19): R19
  (...args: O20): R20
  (...args: O21): R21
  (...args: O22): R22
  (...args: O23): R23
}
type TuplesToRecord23<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
  A19,
  R19,
  A20,
  R20,
  A21,
  R21,
  A22,
  R22,
  A23,
  R23,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {}) &
  (A19 extends [string, ...any] ? { [K in A19[0]]: R19 } : {}) &
  (A20 extends [string, ...any] ? { [K in A20[0]]: R20 } : {}) &
  (A21 extends [string, ...any] ? { [K in A21[0]]: R21 } : {}) &
  (A22 extends [string, ...any] ? { [K in A22[0]]: R22 } : {}) &
  (A23 extends [string, ...any] ? { [K in A23[0]]: R23 } : {})
interface Overloaded24<
  O1 extends any[],
  R1 extends any,
  O2 extends any[],
  R2 extends any,
  O3 extends any[],
  R3 extends any,
  O4 extends any[],
  R4 extends any,
  O5 extends any[],
  R5 extends any,
  O6 extends any[],
  R6 extends any,
  O7 extends any[],
  R7 extends any,
  O8 extends any[],
  R8 extends any,
  O9 extends any[],
  R9 extends any,
  O10 extends any[],
  R10 extends any,
  O11 extends any[],
  R11 extends any,
  O12 extends any[],
  R12 extends any,
  O13 extends any[],
  R13 extends any,
  O14 extends any[],
  R14 extends any,
  O15 extends any[],
  R15 extends any,
  O16 extends any[],
  R16 extends any,
  O17 extends any[],
  R17 extends any,
  O18 extends any[],
  R18 extends any,
  O19 extends any[],
  R19 extends any,
  O20 extends any[],
  R20 extends any,
  O21 extends any[],
  R21 extends any,
  O22 extends any[],
  R22 extends any,
  O23 extends any[],
  R23 extends any,
  O24 extends any[],
  R24 extends any,
> {
  (...args: O1): R1
  (...args: O2): R2
  (...args: O3): R3
  (...args: O4): R4
  (...args: O5): R5
  (...args: O6): R6
  (...args: O7): R7
  (...args: O8): R8
  (...args: O9): R9
  (...args: O10): R10
  (...args: O11): R11
  (...args: O12): R12
  (...args: O13): R13
  (...args: O14): R14
  (...args: O15): R15
  (...args: O16): R16
  (...args: O17): R17
  (...args: O18): R18
  (...args: O19): R19
  (...args: O20): R20
  (...args: O21): R21
  (...args: O22): R22
  (...args: O23): R23
  (...args: O24): R24
}
type TuplesToRecord24<
  A1,
  R1,
  A2,
  R2,
  A3,
  R3,
  A4,
  R4,
  A5,
  R5,
  A6,
  R6,
  A7,
  R7,
  A8,
  R8,
  A9,
  R9,
  A10,
  R10,
  A11,
  R11,
  A12,
  R12,
  A13,
  R13,
  A14,
  R14,
  A15,
  R15,
  A16,
  R16,
  A17,
  R17,
  A18,
  R18,
  A19,
  R19,
  A20,
  R20,
  A21,
  R21,
  A22,
  R22,
  A23,
  R23,
  A24,
  R24,
> = (A1 extends [string, ...any] ? { [K in A1[0]]: R1 } : {}) &
  (A2 extends [string, ...any] ? { [K in A2[0]]: R2 } : {}) &
  (A3 extends [string, ...any] ? { [K in A3[0]]: R3 } : {}) &
  (A4 extends [string, ...any] ? { [K in A4[0]]: R4 } : {}) &
  (A5 extends [string, ...any] ? { [K in A5[0]]: R5 } : {}) &
  (A6 extends [string, ...any] ? { [K in A6[0]]: R6 } : {}) &
  (A7 extends [string, ...any] ? { [K in A7[0]]: R7 } : {}) &
  (A8 extends [string, ...any] ? { [K in A8[0]]: R8 } : {}) &
  (A9 extends [string, ...any] ? { [K in A9[0]]: R9 } : {}) &
  (A10 extends [string, ...any] ? { [K in A10[0]]: R10 } : {}) &
  (A11 extends [string, ...any] ? { [K in A11[0]]: R11 } : {}) &
  (A12 extends [string, ...any] ? { [K in A12[0]]: R12 } : {}) &
  (A13 extends [string, ...any] ? { [K in A13[0]]: R13 } : {}) &
  (A14 extends [string, ...any] ? { [K in A14[0]]: R14 } : {}) &
  (A15 extends [string, ...any] ? { [K in A15[0]]: R15 } : {}) &
  (A16 extends [string, ...any] ? { [K in A16[0]]: R16 } : {}) &
  (A17 extends [string, ...any] ? { [K in A17[0]]: R17 } : {}) &
  (A18 extends [string, ...any] ? { [K in A18[0]]: R18 } : {}) &
  (A19 extends [string, ...any] ? { [K in A19[0]]: R19 } : {}) &
  (A20 extends [string, ...any] ? { [K in A20[0]]: R20 } : {}) &
  (A21 extends [string, ...any] ? { [K in A21[0]]: R21 } : {}) &
  (A22 extends [string, ...any] ? { [K in A22[0]]: R22 } : {}) &
  (A23 extends [string, ...any] ? { [K in A23[0]]: R23 } : {}) &
  (A24 extends [string, ...any] ? { [K in A24[0]]: R24 } : {})
export type OverloadedInputResultMap<T> =
  T extends Overloaded24<
    infer A1,
    infer R1,
    infer A2,
    infer R2,
    infer A3,
    infer R3,
    infer A4,
    infer R4,
    infer A5,
    infer R5,
    infer A6,
    infer R6,
    infer A7,
    infer R7,
    infer A8,
    infer R8,
    infer A9,
    infer R9,
    infer A10,
    infer R10,
    infer A11,
    infer R11,
    infer A12,
    infer R12,
    infer A13,
    infer R13,
    infer A14,
    infer R14,
    infer A15,
    infer R15,
    infer A16,
    infer R16,
    infer A17,
    infer R17,
    infer A18,
    infer R18,
    infer A19,
    infer R19,
    infer A20,
    infer R20,
    infer A21,
    infer R21,
    infer A22,
    infer R22,
    infer A23,
    infer R23,
    infer A24,
    infer R24
  >
    ? TuplesToRecord24<
        A1,
        R1,
        A2,
        R2,
        A3,
        R3,
        A4,
        R4,
        A5,
        R5,
        A6,
        R6,
        A7,
        R7,
        A8,
        R8,
        A9,
        R9,
        A10,
        R10,
        A11,
        R11,
        A12,
        R12,
        A13,
        R13,
        A14,
        R14,
        A15,
        R15,
        A16,
        R16,
        A17,
        R17,
        A18,
        R18,
        A19,
        R19,
        A20,
        R20,
        A21,
        R21,
        A22,
        R22,
        A23,
        R23,
        A24,
        R24
      >
    : T extends Overloaded23<
          infer A1,
          infer R1,
          infer A2,
          infer R2,
          infer A3,
          infer R3,
          infer A4,
          infer R4,
          infer A5,
          infer R5,
          infer A6,
          infer R6,
          infer A7,
          infer R7,
          infer A8,
          infer R8,
          infer A9,
          infer R9,
          infer A10,
          infer R10,
          infer A11,
          infer R11,
          infer A12,
          infer R12,
          infer A13,
          infer R13,
          infer A14,
          infer R14,
          infer A15,
          infer R15,
          infer A16,
          infer R16,
          infer A17,
          infer R17,
          infer A18,
          infer R18,
          infer A19,
          infer R19,
          infer A20,
          infer R20,
          infer A21,
          infer R21,
          infer A22,
          infer R22,
          infer A23,
          infer R23
        >
      ? TuplesToRecord23<
          A1,
          R1,
          A2,
          R2,
          A3,
          R3,
          A4,
          R4,
          A5,
          R5,
          A6,
          R6,
          A7,
          R7,
          A8,
          R8,
          A9,
          R9,
          A10,
          R10,
          A11,
          R11,
          A12,
          R12,
          A13,
          R13,
          A14,
          R14,
          A15,
          R15,
          A16,
          R16,
          A17,
          R17,
          A18,
          R18,
          A19,
          R19,
          A20,
          R20,
          A21,
          R21,
          A22,
          R22,
          A23,
          R23
        >
      : T extends Overloaded22<
            infer A1,
            infer R1,
            infer A2,
            infer R2,
            infer A3,
            infer R3,
            infer A4,
            infer R4,
            infer A5,
            infer R5,
            infer A6,
            infer R6,
            infer A7,
            infer R7,
            infer A8,
            infer R8,
            infer A9,
            infer R9,
            infer A10,
            infer R10,
            infer A11,
            infer R11,
            infer A12,
            infer R12,
            infer A13,
            infer R13,
            infer A14,
            infer R14,
            infer A15,
            infer R15,
            infer A16,
            infer R16,
            infer A17,
            infer R17,
            infer A18,
            infer R18,
            infer A19,
            infer R19,
            infer A20,
            infer R20,
            infer A21,
            infer R21,
            infer A22,
            infer R22
          >
        ? TuplesToRecord22<
            A1,
            R1,
            A2,
            R2,
            A3,
            R3,
            A4,
            R4,
            A5,
            R5,
            A6,
            R6,
            A7,
            R7,
            A8,
            R8,
            A9,
            R9,
            A10,
            R10,
            A11,
            R11,
            A12,
            R12,
            A13,
            R13,
            A14,
            R14,
            A15,
            R15,
            A16,
            R16,
            A17,
            R17,
            A18,
            R18,
            A19,
            R19,
            A20,
            R20,
            A21,
            R21,
            A22,
            R22
          >
        : T extends Overloaded21<
              infer A1,
              infer R1,
              infer A2,
              infer R2,
              infer A3,
              infer R3,
              infer A4,
              infer R4,
              infer A5,
              infer R5,
              infer A6,
              infer R6,
              infer A7,
              infer R7,
              infer A8,
              infer R8,
              infer A9,
              infer R9,
              infer A10,
              infer R10,
              infer A11,
              infer R11,
              infer A12,
              infer R12,
              infer A13,
              infer R13,
              infer A14,
              infer R14,
              infer A15,
              infer R15,
              infer A16,
              infer R16,
              infer A17,
              infer R17,
              infer A18,
              infer R18,
              infer A19,
              infer R19,
              infer A20,
              infer R20,
              infer A21,
              infer R21
            >
          ? TuplesToRecord21<
              A1,
              R1,
              A2,
              R2,
              A3,
              R3,
              A4,
              R4,
              A5,
              R5,
              A6,
              R6,
              A7,
              R7,
              A8,
              R8,
              A9,
              R9,
              A10,
              R10,
              A11,
              R11,
              A12,
              R12,
              A13,
              R13,
              A14,
              R14,
              A15,
              R15,
              A16,
              R16,
              A17,
              R17,
              A18,
              R18,
              A19,
              R19,
              A20,
              R20,
              A21,
              R21
            >
          : T extends Overloaded20<
                infer A1,
                infer R1,
                infer A2,
                infer R2,
                infer A3,
                infer R3,
                infer A4,
                infer R4,
                infer A5,
                infer R5,
                infer A6,
                infer R6,
                infer A7,
                infer R7,
                infer A8,
                infer R8,
                infer A9,
                infer R9,
                infer A10,
                infer R10,
                infer A11,
                infer R11,
                infer A12,
                infer R12,
                infer A13,
                infer R13,
                infer A14,
                infer R14,
                infer A15,
                infer R15,
                infer A16,
                infer R16,
                infer A17,
                infer R17,
                infer A18,
                infer R18,
                infer A19,
                infer R19,
                infer A20,
                infer R20
              >
            ? TuplesToRecord20<
                A1,
                R1,
                A2,
                R2,
                A3,
                R3,
                A4,
                R4,
                A5,
                R5,
                A6,
                R6,
                A7,
                R7,
                A8,
                R8,
                A9,
                R9,
                A10,
                R10,
                A11,
                R11,
                A12,
                R12,
                A13,
                R13,
                A14,
                R14,
                A15,
                R15,
                A16,
                R16,
                A17,
                R17,
                A18,
                R18,
                A19,
                R19,
                A20,
                R20
              >
            : T extends Overloaded19<
                  infer A1,
                  infer R1,
                  infer A2,
                  infer R2,
                  infer A3,
                  infer R3,
                  infer A4,
                  infer R4,
                  infer A5,
                  infer R5,
                  infer A6,
                  infer R6,
                  infer A7,
                  infer R7,
                  infer A8,
                  infer R8,
                  infer A9,
                  infer R9,
                  infer A10,
                  infer R10,
                  infer A11,
                  infer R11,
                  infer A12,
                  infer R12,
                  infer A13,
                  infer R13,
                  infer A14,
                  infer R14,
                  infer A15,
                  infer R15,
                  infer A16,
                  infer R16,
                  infer A17,
                  infer R17,
                  infer A18,
                  infer R18,
                  infer A19,
                  infer R19
                >
              ? TuplesToRecord19<
                  A1,
                  R1,
                  A2,
                  R2,
                  A3,
                  R3,
                  A4,
                  R4,
                  A5,
                  R5,
                  A6,
                  R6,
                  A7,
                  R7,
                  A8,
                  R8,
                  A9,
                  R9,
                  A10,
                  R10,
                  A11,
                  R11,
                  A12,
                  R12,
                  A13,
                  R13,
                  A14,
                  R14,
                  A15,
                  R15,
                  A16,
                  R16,
                  A17,
                  R17,
                  A18,
                  R18,
                  A19,
                  R19
                >
              : T extends Overloaded18<
                    infer A1,
                    infer R1,
                    infer A2,
                    infer R2,
                    infer A3,
                    infer R3,
                    infer A4,
                    infer R4,
                    infer A5,
                    infer R5,
                    infer A6,
                    infer R6,
                    infer A7,
                    infer R7,
                    infer A8,
                    infer R8,
                    infer A9,
                    infer R9,
                    infer A10,
                    infer R10,
                    infer A11,
                    infer R11,
                    infer A12,
                    infer R12,
                    infer A13,
                    infer R13,
                    infer A14,
                    infer R14,
                    infer A15,
                    infer R15,
                    infer A16,
                    infer R16,
                    infer A17,
                    infer R17,
                    infer A18,
                    infer R18
                  >
                ? TuplesToRecord18<
                    A1,
                    R1,
                    A2,
                    R2,
                    A3,
                    R3,
                    A4,
                    R4,
                    A5,
                    R5,
                    A6,
                    R6,
                    A7,
                    R7,
                    A8,
                    R8,
                    A9,
                    R9,
                    A10,
                    R10,
                    A11,
                    R11,
                    A12,
                    R12,
                    A13,
                    R13,
                    A14,
                    R14,
                    A15,
                    R15,
                    A16,
                    R16,
                    A17,
                    R17,
                    A18,
                    R18
                  >
                : T extends Overloaded17<
                      infer A1,
                      infer R1,
                      infer A2,
                      infer R2,
                      infer A3,
                      infer R3,
                      infer A4,
                      infer R4,
                      infer A5,
                      infer R5,
                      infer A6,
                      infer R6,
                      infer A7,
                      infer R7,
                      infer A8,
                      infer R8,
                      infer A9,
                      infer R9,
                      infer A10,
                      infer R10,
                      infer A11,
                      infer R11,
                      infer A12,
                      infer R12,
                      infer A13,
                      infer R13,
                      infer A14,
                      infer R14,
                      infer A15,
                      infer R15,
                      infer A16,
                      infer R16,
                      infer A17,
                      infer R17
                    >
                  ? TuplesToRecord17<
                      A1,
                      R1,
                      A2,
                      R2,
                      A3,
                      R3,
                      A4,
                      R4,
                      A5,
                      R5,
                      A6,
                      R6,
                      A7,
                      R7,
                      A8,
                      R8,
                      A9,
                      R9,
                      A10,
                      R10,
                      A11,
                      R11,
                      A12,
                      R12,
                      A13,
                      R13,
                      A14,
                      R14,
                      A15,
                      R15,
                      A16,
                      R16,
                      A17,
                      R17
                    >
                  : T extends Overloaded16<
                        infer A1,
                        infer R1,
                        infer A2,
                        infer R2,
                        infer A3,
                        infer R3,
                        infer A4,
                        infer R4,
                        infer A5,
                        infer R5,
                        infer A6,
                        infer R6,
                        infer A7,
                        infer R7,
                        infer A8,
                        infer R8,
                        infer A9,
                        infer R9,
                        infer A10,
                        infer R10,
                        infer A11,
                        infer R11,
                        infer A12,
                        infer R12,
                        infer A13,
                        infer R13,
                        infer A14,
                        infer R14,
                        infer A15,
                        infer R15,
                        infer A16,
                        infer R16
                      >
                    ? TuplesToRecord16<
                        A1,
                        R1,
                        A2,
                        R2,
                        A3,
                        R3,
                        A4,
                        R4,
                        A5,
                        R5,
                        A6,
                        R6,
                        A7,
                        R7,
                        A8,
                        R8,
                        A9,
                        R9,
                        A10,
                        R10,
                        A11,
                        R11,
                        A12,
                        R12,
                        A13,
                        R13,
                        A14,
                        R14,
                        A15,
                        R15,
                        A16,
                        R16
                      >
                    : T extends Overloaded15<
                          infer A1,
                          infer R1,
                          infer A2,
                          infer R2,
                          infer A3,
                          infer R3,
                          infer A4,
                          infer R4,
                          infer A5,
                          infer R5,
                          infer A6,
                          infer R6,
                          infer A7,
                          infer R7,
                          infer A8,
                          infer R8,
                          infer A9,
                          infer R9,
                          infer A10,
                          infer R10,
                          infer A11,
                          infer R11,
                          infer A12,
                          infer R12,
                          infer A13,
                          infer R13,
                          infer A14,
                          infer R14,
                          infer A15,
                          infer R15
                        >
                      ? TuplesToRecord15<
                          A1,
                          R1,
                          A2,
                          R2,
                          A3,
                          R3,
                          A4,
                          R4,
                          A5,
                          R5,
                          A6,
                          R6,
                          A7,
                          R7,
                          A8,
                          R8,
                          A9,
                          R9,
                          A10,
                          R10,
                          A11,
                          R11,
                          A12,
                          R12,
                          A13,
                          R13,
                          A14,
                          R14,
                          A15,
                          R15
                        >
                      : T extends Overloaded14<
                            infer A1,
                            infer R1,
                            infer A2,
                            infer R2,
                            infer A3,
                            infer R3,
                            infer A4,
                            infer R4,
                            infer A5,
                            infer R5,
                            infer A6,
                            infer R6,
                            infer A7,
                            infer R7,
                            infer A8,
                            infer R8,
                            infer A9,
                            infer R9,
                            infer A10,
                            infer R10,
                            infer A11,
                            infer R11,
                            infer A12,
                            infer R12,
                            infer A13,
                            infer R13,
                            infer A14,
                            infer R14
                          >
                        ? TuplesToRecord14<
                            A1,
                            R1,
                            A2,
                            R2,
                            A3,
                            R3,
                            A4,
                            R4,
                            A5,
                            R5,
                            A6,
                            R6,
                            A7,
                            R7,
                            A8,
                            R8,
                            A9,
                            R9,
                            A10,
                            R10,
                            A11,
                            R11,
                            A12,
                            R12,
                            A13,
                            R13,
                            A14,
                            R14
                          >
                        : T extends Overloaded13<
                              infer A1,
                              infer R1,
                              infer A2,
                              infer R2,
                              infer A3,
                              infer R3,
                              infer A4,
                              infer R4,
                              infer A5,
                              infer R5,
                              infer A6,
                              infer R6,
                              infer A7,
                              infer R7,
                              infer A8,
                              infer R8,
                              infer A9,
                              infer R9,
                              infer A10,
                              infer R10,
                              infer A11,
                              infer R11,
                              infer A12,
                              infer R12,
                              infer A13,
                              infer R13
                            >
                          ? TuplesToRecord13<
                              A1,
                              R1,
                              A2,
                              R2,
                              A3,
                              R3,
                              A4,
                              R4,
                              A5,
                              R5,
                              A6,
                              R6,
                              A7,
                              R7,
                              A8,
                              R8,
                              A9,
                              R9,
                              A10,
                              R10,
                              A11,
                              R11,
                              A12,
                              R12,
                              A13,
                              R13
                            >
                          : T extends Overloaded12<
                                infer A1,
                                infer R1,
                                infer A2,
                                infer R2,
                                infer A3,
                                infer R3,
                                infer A4,
                                infer R4,
                                infer A5,
                                infer R5,
                                infer A6,
                                infer R6,
                                infer A7,
                                infer R7,
                                infer A8,
                                infer R8,
                                infer A9,
                                infer R9,
                                infer A10,
                                infer R10,
                                infer A11,
                                infer R11,
                                infer A12,
                                infer R12
                              >
                            ? TuplesToRecord12<
                                A1,
                                R1,
                                A2,
                                R2,
                                A3,
                                R3,
                                A4,
                                R4,
                                A5,
                                R5,
                                A6,
                                R6,
                                A7,
                                R7,
                                A8,
                                R8,
                                A9,
                                R9,
                                A10,
                                R10,
                                A11,
                                R11,
                                A12,
                                R12
                              >
                            : T extends Overloaded11<
                                  infer A1,
                                  infer R1,
                                  infer A2,
                                  infer R2,
                                  infer A3,
                                  infer R3,
                                  infer A4,
                                  infer R4,
                                  infer A5,
                                  infer R5,
                                  infer A6,
                                  infer R6,
                                  infer A7,
                                  infer R7,
                                  infer A8,
                                  infer R8,
                                  infer A9,
                                  infer R9,
                                  infer A10,
                                  infer R10,
                                  infer A11,
                                  infer R11
                                >
                              ? TuplesToRecord11<
                                  A1,
                                  R1,
                                  A2,
                                  R2,
                                  A3,
                                  R3,
                                  A4,
                                  R4,
                                  A5,
                                  R5,
                                  A6,
                                  R6,
                                  A7,
                                  R7,
                                  A8,
                                  R8,
                                  A9,
                                  R9,
                                  A10,
                                  R10,
                                  A11,
                                  R11
                                >
                              : T extends Overloaded10<
                                    infer A1,
                                    infer R1,
                                    infer A2,
                                    infer R2,
                                    infer A3,
                                    infer R3,
                                    infer A4,
                                    infer R4,
                                    infer A5,
                                    infer R5,
                                    infer A6,
                                    infer R6,
                                    infer A7,
                                    infer R7,
                                    infer A8,
                                    infer R8,
                                    infer A9,
                                    infer R9,
                                    infer A10,
                                    infer R10
                                  >
                                ? TuplesToRecord10<
                                    A1,
                                    R1,
                                    A2,
                                    R2,
                                    A3,
                                    R3,
                                    A4,
                                    R4,
                                    A5,
                                    R5,
                                    A6,
                                    R6,
                                    A7,
                                    R7,
                                    A8,
                                    R8,
                                    A9,
                                    R9,
                                    A10,
                                    R10
                                  >
                                : T extends Overloaded9<
                                      infer A1,
                                      infer R1,
                                      infer A2,
                                      infer R2,
                                      infer A3,
                                      infer R3,
                                      infer A4,
                                      infer R4,
                                      infer A5,
                                      infer R5,
                                      infer A6,
                                      infer R6,
                                      infer A7,
                                      infer R7,
                                      infer A8,
                                      infer R8,
                                      infer A9,
                                      infer R9
                                    >
                                  ? TuplesToRecord9<
                                      A1,
                                      R1,
                                      A2,
                                      R2,
                                      A3,
                                      R3,
                                      A4,
                                      R4,
                                      A5,
                                      R5,
                                      A6,
                                      R6,
                                      A7,
                                      R7,
                                      A8,
                                      R8,
                                      A9,
                                      R9
                                    >
                                  : T extends Overloaded8<
                                        infer A1,
                                        infer R1,
                                        infer A2,
                                        infer R2,
                                        infer A3,
                                        infer R3,
                                        infer A4,
                                        infer R4,
                                        infer A5,
                                        infer R5,
                                        infer A6,
                                        infer R6,
                                        infer A7,
                                        infer R7,
                                        infer A8,
                                        infer R8
                                      >
                                    ? TuplesToRecord8<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7, A8, R8>
                                    : T extends Overloaded7<
                                          infer A1,
                                          infer R1,
                                          infer A2,
                                          infer R2,
                                          infer A3,
                                          infer R3,
                                          infer A4,
                                          infer R4,
                                          infer A5,
                                          infer R5,
                                          infer A6,
                                          infer R6,
                                          infer A7,
                                          infer R7
                                        >
                                      ? TuplesToRecord7<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6, A7, R7>
                                      : T extends Overloaded6<
                                            infer A1,
                                            infer R1,
                                            infer A2,
                                            infer R2,
                                            infer A3,
                                            infer R3,
                                            infer A4,
                                            infer R4,
                                            infer A5,
                                            infer R5,
                                            infer A6,
                                            infer R6
                                          >
                                        ? TuplesToRecord6<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5, A6, R6>
                                        : T extends Overloaded5<
                                              infer A1,
                                              infer R1,
                                              infer A2,
                                              infer R2,
                                              infer A3,
                                              infer R3,
                                              infer A4,
                                              infer R4,
                                              infer A5,
                                              infer R5
                                            >
                                          ? TuplesToRecord5<A1, R1, A2, R2, A3, R3, A4, R4, A5, R5>
                                          : T extends Overloaded4<
                                                infer A1,
                                                infer R1,
                                                infer A2,
                                                infer R2,
                                                infer A3,
                                                infer R3,
                                                infer A4,
                                                infer R4
                                              >
                                            ? TuplesToRecord4<A1, R1, A2, R2, A3, R3, A4, R4>
                                            : T extends Overloaded3<
                                                  infer A1,
                                                  infer R1,
                                                  infer A2,
                                                  infer R2,
                                                  infer A3,
                                                  infer R3
                                                >
                                              ? TuplesToRecord3<A1, R1, A2, R2, A3, R3>
                                              : T extends Overloaded2<infer A1, infer R1, infer A2, infer R2>
                                                ? TuplesToRecord2<A1, R1, A2, R2>
                                                : T extends Overloaded1<infer A1, infer R1>
                                                  ? TuplesToRecord1<A1, R1>
                                                  : never
