name: Checks and Linters

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@3b91bdb6e6078574c4f436509af2193e293c1e43 # master
    permissions:
      security-events: write
      contents: read

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@3b91bdb6e6078574c4f436509af2193e293c1e43 # master

  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1
        with:
          version: v1.8.1

      - name: Check formatting with prettier
        run: npm run prettier:check

      - name: Check Solidity formatting with forge fmt
        run: npm run fmt:sol:check

      - name: Lint with ESLint
        run: npm run lint
