---
name: Tests runner
on:
  pull_request:

jobs:
  tests:
    services:
      hardhat-node:
        image: ghcr.io/lidofinance/hardhat-node:2.22.12
        ports:
          - 8545:8545
        env:
          INFURA_TOKEN: ${{ secrets.INFURA_TOKEN }}

    name: JS tests
    runs-on: ubuntu-latest
    env:
      ALCHEMY_TOKEN: not-so-secret-token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Generate typechain
        env:
          SKIP_TYPECHAIN: true
        run: pnpm run typechain

      - name: Run unit tests
        run: pnpm run test
