// Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
// Contract: SetDepositsReserveTarget
// Source: Etherscan, hoodi 0x68009122a394504E8fD7fee58F92Cd73c6A60717 (SetDepositsReserveTarget)

export const SetDepositsReserveTarget_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_trustedCaller", type: "address" },
      { internalType: "uint256", name: "_maxDepositsReserveTarget", type: "uint256" },
      { internalType: "address", name: "_lido", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "MAX_DEPOSITS_RESERVE_TARGET",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_creator", type: "address" },
      { internalType: "bytes", name: "_evmScriptCallData", type: "bytes" },
    ],
    name: "createEVMScript",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "_evmScriptCallData", type: "bytes" }],
    name: "decodeEVMScriptCallData",
    outputs: [{ internalType: "uint256", name: "newDepositsReserveTarget", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "lido",
    outputs: [{ internalType: "contract ILido", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trustedCaller",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
