// Generated by `npm run abi:sync` — do not edit by hand, re-run the command instead.
// Contract: TimeConstraints
// Source: Etherscan, mainnet 0x2a30F5aC03187674553024296bed35Aa49749DDa (TimeConstraints)

export const TimeConstraints_ABI = [
  {
    inputs: [
      { internalType: "Duration", name: "currentDayTime", type: "uint32" },
      { internalType: "Duration", name: "startDayTime", type: "uint32" },
      { internalType: "Duration", name: "endDayTime", type: "uint32" },
    ],
    name: "DayTimeOutOfRange",
    type: "error",
  },
  { inputs: [], name: "DayTimeOverflow", type: "error" },
  { inputs: [], name: "DurationOverflow", type: "error" },
  {
    inputs: [{ internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "TimestampNotPassed",
    type: "error",
  },
  {
    inputs: [{ internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "TimestampPassed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "TimeAfterTimestampChecked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "TimeBeforeTimestampChecked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "Duration", name: "startDayTime", type: "uint32" },
      { indexed: false, internalType: "Duration", name: "endDayTime", type: "uint32" },
    ],
    name: "TimeWithinDayTimeChecked",
    type: "event",
  },
  {
    inputs: [],
    name: "DAY_DURATION",
    outputs: [{ internalType: "Duration", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "checkTimeAfterTimestamp",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "checkTimeAfterTimestampAndEmit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "checkTimeBeforeTimestamp",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "Timestamp", name: "timestamp", type: "uint40" }],
    name: "checkTimeBeforeTimestampAndEmit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "Duration", name: "startDayTime", type: "uint32" },
      { internalType: "Duration", name: "endDayTime", type: "uint32" },
    ],
    name: "checkTimeWithinDayTime",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "Duration", name: "startDayTime", type: "uint32" },
      { internalType: "Duration", name: "endDayTime", type: "uint32" },
    ],
    name: "checkTimeWithinDayTimeAndEmit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentDayTime",
    outputs: [{ internalType: "Duration", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
